### ISSUE TITLE
Issue with "Start Tracking Time" Button in Stream Deck on MacOS

### ISSUE THREAD

**Issue by jziebacreatuity** [clamburger/everhour-for-stream-deck#6]
Hello,

I've encountered an issue with the "Start Tracking Time" button functionality in my Stream Deck plugin. Despite entering the API token correctly, the button does not function properly. Other features of the plugin, such as "Resume", "Stop Timer", and "Active Task", are working fine.

Details of the issue:

Task ID: I am using a format "two letters:number-number", which is different from the format presented in the README documentation where numbers are separated by hyphens. I'm unsure if this could be the cause of the issue.
Error Signal: Upon pressing the button on the Stream Deck, a yellow exclamation mark appears, indicating an error.
Plugin Version: I am using version 1.0.1.
Operating System: MacOS.
Hardware: Standard Stream Deck.
Could I please request assistance in resolving this issue? Is there a known issue with the Task ID format, or could there be other factors affecting this problem?

https://github.com/clamburger/everhour-for-stream-deck/assets/127491398/06d5b176-910d-42ea-95da-c70ef7d7277d

Thank you in advance for your help.

**Comment by clamburger** [comment]
The grey play button means that the plugin thinks there's no task ID set for that button. I've noticed that sometimes the task ID doesn't get saved correctly, although it's usually fine after a restart. I'll experiment further once I have my Stream Deck in front of me.

Your task ID format sounds correct; the string with dashes is the API Token, and since your other buttons are working that means that API Token is set correctly.

Can I confirm that your button config looks something like this:

![image](https://github.com/clamburger/everhour-for-stream-deck/assets/1396298/02532b94-03b1-4809-8994-edfa5d415bea)

May I also get an example of the task ID you're using? You can replace the numbers with zeroes.

**Comment by jziebacreatuity** [comment]
Yes, I agree. After resetting the Stream Deck app, everything often starts working correctly. This seems to be an issue related to Stream Deck itself, as I have noticed similar behavior when using several different plugins. It would be a good idea to add information in the settings or in the user guide that resetting the Stream Deck app can help resolve issues. This is often an effective way to solve minor technical problems. Thanks a lot! Great plugin!
